//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imprest.Models.Imprest.en
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionReport
    {
        public string TransactionNo { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<bool> credit { get; set; }
        public string voucherType { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<bool> BrsDone { get; set; }
        public string ChequeNo { get; set; }
        public Nullable<System.DateTime> ChequeDate { get; set; }
        public string Narration { get; set; }
        public string ProjectNo { get; set; }
        public Nullable<int> ProjectType { get; set; }
        public string SupplierName { get; set; }
        public Nullable<System.DateTime> VoucherDate { get; set; }
    }
}
